name: Build and Release .deb Package

on:
  push:
    branches:
      - develop
    # tags:
    #   - 'v*.*.*'  # Triggered only when pushing tags in the format v0.1.0

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-stdeb \
            dh-python \
            debhelper \
            fakeroot

      - name: Build .deb package
        run: |
          python3 setup.py --command-packages=stdeb.command bdist_deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: deb_dist/*.deb
      - name: Show current directory
        run: pwd

      - name: Prepare directory for deb package
        run: mkdir -p release

      - name: List files
        run: ls -la

      - name: Build DEB package
        run: python3 setup.py --command-packages=stdeb.command bdist_deb

      - name: Move built deb package to the release directory
        run: mv deb_dist/*.deb release/

  release:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Echo works
        run: echo "works"