name: Build and Release .deb Package

on:
  push:
    tags:
      - 'v*.*.*'  # Triggered only when pushing tags in the format v0.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-stdeb dh-python python3-all build-essential debhelper
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools psutil stdeb

      - name: Show current directory
        run: pwd

      - name: Prepare directory for deb package
        run: mkdir -p release

      - name: List files
        run: ls -la

      - name: Build DEB package
        run: python3 setup.py --command-packages=stdeb.command bdist_deb

      - name: Move built deb package to the release directory
        run: mv deb_dist/*.deb release/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Echo works
        run: echo "works"
